Import the libraries.

In [3]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

Make a synthetic regression dataset.

In [ ]:
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50) # Create a dataset with 100 samples, 2 features, and some noise
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y}) # Create a DataFrame from the generated dataset
df.shape

(100, 3)

In [5]:
df.head()

,feature1,feature2,target
0,1.747559,-1.259893,61.401316
1,-1.725067,-1.142308,-196.312776
2,-0.847179,-2.523321,-193.719918
3,0.665226,-1.313138,-92.242666
4,-0.267084,-0.122374,-45.283884


Plot the data.

In [6]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')
fig.show()

Train test split.

In [7]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
y_pred

array([ -42.58254588,   13.74780344,   48.21805207,  -67.42580141,
         15.52896433,   63.51482937,   25.63195134,   43.43342883,
         90.08835539,   88.76538245, -307.56533716,   43.31629228,
       -140.86808655,  175.92858042, -167.58323931,  -34.89399169,
         96.39090172,   12.67998399,  -65.79191412,   78.20536357])

Print the values of regression metrics.

In [8]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 Score",r2_score(y_test,y_pred))

MAE 38.83183083292764
MSE 2664.293874734137
R2 Score 0.8172572244035216


Create x and y and their predicted result in z.

In [ ]:
x = np.linspace(-5, 5, 10) # 10 points from -5 to 5 for feature1
y = np.linspace(-5, 5, 10) # 10 points from -5 to 5 for feature2

xGrid, yGrid = np.meshgrid(x, y) # Create a grid of points for feature1 and feature2

final = np.vstack((xGrid.ravel(), yGrid.ravel())).T # Combine the grid points into a 2D array of shape (100, 2)

z_final = lr.predict(final).reshape(10, 10) # Reshape the predicted values into a 10x10 grid

z = z_final

Plot.

In [10]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()
     

lr.coef_, lr.intercept_


(array([96.09218935, 61.47776624]), np.float64(-1.7060202931873611))

Load a sklearn dataset.

In [11]:
import numpy as np
from sklearn.datasets import load_diabetes
X,y = load_diabetes(return_X_y=True)
X,y

(array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]], shape=(442, 10)),
 array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59.

Train test split.

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((353, 10), (89, 10), (353,), (89,))

Train model on linear regression.

In [13]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)
lr.coef_, lr.intercept_

(array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]),
 np.float64(151.88331005254167))

In [14]:
y_pred = lr.predict(x_test)
y_pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [15]:
from sklearn.metrics import r2_score
print("R2 Score",r2_score(y_test,y_pred))

R2 Score 0.4399338661568968


In [16]:
lr.coef_, lr.intercept_

(array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]),
 np.float64(151.88331005254167))

Make a Multiple Regression class.

In [17]:
class SelfMadeRegression:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self, x_train, y_train):
        x_train = np.insert(x_train, 0, 1, axis=1)
        x_transpose = x_train.T

        betas = np.linalg.inv(x_transpose.dot(x_train)).dot(x_transpose).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
    
    def predict(self, x_test):
        return x_test.dot(self.coef_) + self.intercept_

Train the model.

In [19]:
lr = SelfMadeRegression()
lr.fit(x_train, y_train)
np.insert(x_test, 0, 1, axis=1)
y_pred = lr.predict(x_test)
y_pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [20]:
print("R2 Score",r2_score(y_test,y_pred))
print(lr.coef_, lr.intercept_)

R2 Score 0.43993386615689634
[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238] 151.88331005254165
