Import the libraries.

In [18]:
import numpy as np
import pandas as pd

Create a dataframe.

In [19]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


Self made functions.

Function to initialize the parameters.

In [20]:
def init_params(layer_dims): # Function to initialize parameters
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims) # number of layers in the network
    
    for l in range(1, L):
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
    return parameters

In [21]:
init_params([2, 2, 1])

{'W1': array([[ 0.01788628,  0.0043651 ],
        [ 0.00096497, -0.01863493]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[-0.00277388, -0.00354759]]),
 'b2': array([[0.]])}

Z = W.A + b

In [22]:
def linear_forward(A_prev,W,b):
    Z = np.dot(W,A_prev) + b
    return Z

Function for forward propogation.

In [23]:
def forward_propagation(X, parameters):
    A = X
    L = len(parameters) // 2 # number of layers in the neural network
    
    for l in range(1, L + 1):
        A_prev = A
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        print("A"+str(l-1)+": ", A_prev)
        print("W"+str(l)+": ", Wl)
        print("b"+str(l)+": ", bl)
        print("--"*20)

        A = linear_forward(A_prev, Wl, bl)
        print("A"+str(l)+": ", A)
        print("**"*20)
    return A,A_prev

Find the y_hat for a point.

In [24]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = init_params([2,2,1])

y_hat,A1 = forward_propagation(X, parameters)

A0:  [[8]
 [8]]
W1:  [[ 0.01788628  0.0043651 ]
 [ 0.00096497 -0.01863493]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[ 0.17801107]
 [-0.14135962]]
****************************************
A1:  [[ 0.17801107]
 [-0.14135962]]
W2:  [[-0.00277388 -0.00354759]]
b2:  [[0.]]
----------------------------------------
A2:  [[7.70424482e-06]]
****************************************


Update the paramters using GD.

In [25]:
def update_parameters(parameters,y,y_hat,A1,X):
  error = (y - y_hat).item()

  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * error * A1[0][0])
  parameters['W2'][0][1] = parameters['W2'][0][1] + (0.001 * 2 * error * A1[1][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 * error)

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * error * parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * error * parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * error * parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * error * parameters['W2'][0][1]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * error * parameters['W2'][0][1]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * error * parameters['W2'][0][1])

  return parameters

In [26]:
update_parameters(parameters,y,y_hat,A1,X)

{'W1': array([[ 0.0177999 ,  0.00427871],
        [ 0.00066555, -0.01893435]]),
 'b1': array([[-1.07983491e-05],
        [-3.74276444e-05]]),
 'W2': array([[-0.0013498 , -0.00467846]]),
 'b2': array([[0.00799998]])}

Forward propogation on points of x and find y_pred than update parameters.

In [27]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = init_params([2,2,1])

y_hat,A1 = forward_propagation(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[8]
 [8]]
W1:  [[ 0.01788628  0.0043651 ]
 [ 0.00096497 -0.01863493]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[ 0.17801107]
 [-0.14135962]]
****************************************
A1:  [[ 0.17801107]
 [-0.14135962]]
W2:  [[-0.00277388 -0.00354759]]
b2:  [[0.]]
----------------------------------------
A2:  [[7.70424482e-06]]
****************************************


{'W1': array([[ 0.0177999 ,  0.00427871],
        [ 0.00066555, -0.01893435]]),
 'b1': array([[-1.07983491e-05],
        [-3.74276444e-05]]),
 'W2': array([[-0.0013498 , -0.00467846]]),
 'b2': array([[0.00799998]])}

In [28]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = forward_propagation(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[7]
 [9]]
W1:  [[ 0.0177999   0.00427871]
 [ 0.00066555 -0.01893435]]
b1:  [[-1.07983491e-05]
 [-3.74276444e-05]]
----------------------------------------
A1:  [[ 0.16309689]
 [-0.16578769]]
****************************************
A1:  [[ 0.16309689]
 [-0.16578769]]
W2:  [[-0.0013498  -0.00467846]]
b2:  [[0.00799998]]
----------------------------------------
A2:  [[0.00855547]]
****************************************


{'W1': array([[ 0.01781935,  0.00430372],
        [ 0.00022297, -0.01950339]]),
 'b1': array([[-8.01929305e-06],
        [-1.00654319e-04]]),
 'W2': array([[ 0.00027838, -0.0063335 ]]),
 'b2': array([[0.01798287]])}

In [29]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[2][0]

y_hat,A1 = forward_propagation(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[7]
 [9]]
W1:  [[ 0.01781935  0.00430372]
 [ 0.00022297 -0.01950339]]
b1:  [[-8.01929305e-06]
 [-1.00654319e-04]]
----------------------------------------
A1:  [[ 0.16346095]
 [-0.17407038]]
****************************************
A1:  [[ 0.16346095]
 [-0.17407038]]
W2:  [[ 0.00027838 -0.0063335 ]]
b2:  [[0.01798287]]
----------------------------------------
A2:  [[0.01913085]]
****************************************


{'W1': array([[ 0.01800638,  0.00454419],
        [-0.0004817 , -0.02040938]]),
 'b1': array([[ 1.86991518e-05],
        [-2.01320588e-04]]),
 'W2': array([[ 0.00223366, -0.00841569]]),
 'b2': array([[0.02994461]])}

Repeat the process for epochs.

In [30]:
# epochs implementation

parameters = init_params([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = forward_propagation(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0:  [[8]
 [8]]
W1:  [[ 0.01788628  0.0043651 ]
 [ 0.00096497 -0.01863493]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[ 0.17801107]
 [-0.14135962]]
****************************************
A1:  [[ 0.17801107]
 [-0.14135962]]
W2:  [[-0.00277388 -0.00354759]]
b2:  [[0.]]
----------------------------------------
A2:  [[7.70424482e-06]]
****************************************
A0:  [[7]
 [9]]
W1:  [[ 0.0177999   0.00427871]
 [ 0.00066555 -0.01893435]]
b1:  [[-1.07983491e-05]
 [-3.74276444e-05]]
----------------------------------------
A1:  [[ 0.16309689]
 [-0.16578769]]
****************************************
A1:  [[ 0.16309689]
 [-0.16578769]]
W2:  [[-0.0013498  -0.00467846]]
b2:  [[0.00799998]]
----------------------------------------
A2:  [[0.00855547]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[ 0.01781935  0.00430372]
 [ 0.00022297 -0.01950339]]
b1:  [[-8.01929305e-06]
 [-1.00654319e-04]]
----------------------------------------
A1:  [[ 0

{'W1': array([[ 0.07748461,  0.35689483],
        [-0.10197852, -0.62778871]]),
 'b1': array([[ 0.02394726],
        [-0.04137647]]),
 'W2': array([[ 0.33666799, -0.58856048]]),
 'b2': array([[0.33253231]])}

Demonstration using tenserflow's function.

In [31]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

Making layers structure.

In [33]:
model = Sequential()

model.add(Dense(2, input_dim=2, activation='linear'))
model.add(Dense(1, activation='linear'))    
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

Get the default weights of the model.

In [35]:
model.get_weights()

[array([[-0.98510593, -0.7635734 ],
        [ 0.8523122 , -1.1045132 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.5399928],
        [ 1.2224218]], dtype=float32),
 array([0.], dtype=float32)]

Set the weights to same as self initialized one.

In [39]:
new_weights = [np.array([[0.01, 0.01], [0.01, 0.01]], dtype=np.float32), 
               np.array([0., 0.], dtype=np.float32), 
               np.array([[0.01], [0.01]], dtype=np.float32), 
               np.array([0.], dtype=np.float32)]

In [40]:
model.set_weights(new_weights)

Set the lr of optimizer as same as self made and compile the model.

In [41]:
optimizer = keras.optimizers.SGD(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

Train the model and print the loss.

In [43]:
model.fit(df[['cgpa', 'profile_score']].values, df[['lpa']].values, epochs=75, verbose=1,batch_size=1)

Epoch 1/75
1/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.2246

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3433 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3088 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3161 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2998 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2988 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2863 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2721 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2728 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2524 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2704 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2556 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2312 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2418 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2354 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2241 
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/s